name: Python Environment and Execution

on:
  workflow_dispatch:  # 手动触发器

jobs:
  setup_and_run:
    runs-on: windows-latest  # 在最新的 Windows 环境中运行

    steps:
      - name: Checkout repository  # 检出仓库
        uses: actions/checkout@v5
      
      - name: Set up Python  # 安装 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 指定 Python 版本为 3.x

      - name: Install dependencies  # 安装依赖库
        run: |
          python -m pip install -r requirements.txt

      - name: Run captcha_gen  # 执行 captcha_gen
        run: python captcha_gen.py

      - name: Run captcha_train  # 执行 captcha_train
        run: python captcha_train.py
